# Generated by Django 6.0.1 on 2026-02-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='garaje/')),
                ('enlace', models.URLField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='reconocimientos/')),
                ('imagen', models.ImageField(upload_to='reconocimientos/')),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='referencia',
            name='cargo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referencia',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
