# Generated by Django 6.0.1 on 2026-02-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_garaje_reconocimiento_remove_referencia_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garaje',
            name='enlace',
        ),
        migrations.AddField(
            model_name='garaje',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
            preserve_default=False,
        ),
    ]
